string(ASCII 27 Esc)
set(__256 "${Esc}[38;5")
set(_clrReset "${Esc}[m")
set(_clrCBold  "${Esc}[1m")
set(_clrRed         "${Esc}[31m")
set(_clrGreen       "${Esc}[32m")
set(_clrYellow      "${Esc}[33m")
set(_clr_Yellow     "${__256};228m")
set(_clrBlue        "${Esc}[34m")
set(_clrMagenta     "${Esc}[35m")
set(_clrCyan        "${Esc}[36m")
set(_clrWhite       "${Esc}[37m")
set(_clr_Orange     "${__256};208m")
set(_clrBoldRed     "${Esc}[1;31m")
set(_clrBoldGreen   "${Esc}[1;32m")
set(_clrBoldYellow  "${Esc}[1;33m")
set(_clrBoldBlue    "${Esc}[1;34m")
set(_clrBoldMagenta "${Esc}[1;35m")
set(_clrBoldCyan    "${Esc}[1;36m")
set(_clrBoldWhite   "${Esc}[1;37m")

if(NOT USE_COLOR)
    get_cmake_property(vars VARIABLES)
    foreach(var IN LISTS vars)
        if(var MATCHES "^_clr" AND DEFINED ${var})
            set(${var} "")
        endif()
    endforeach()
else()
    set(CMAKE_COLOR_MAKEFILE ON)
    set(CMAKE_COLOR_DIAGNOSTICS ON)
endif()